name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commitsecret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines
          # git config --global user.email your_email
          # git config --global user.name your_name
          git config --global user.email vmgsahm1@gmail.com
          git config --global user.name TakumaLee
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://${{secrets.commitsecret}}@github.com/TakumaLee/Jumpr-Web.git
          git checkout -b web-pages
          git add --all
          git commit -m "update"
          git push origin web-pages -f
